<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Authors>StarNet</Authors>
    <IsPackable>true</IsPackable>
    <Version>9.1.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Starnet.Testing.Common" Version="1.0.0" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
    <PackageReference Include="xunit.v3.assert" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DStack.Projections\DStack.Projections.csproj" />
  </ItemGroup>

</Project>
